# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Orama' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Orama
  pod 'Alamofire', '5.0.0-beta.2'

  target 'OramaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OramaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
